#!/bin/bash
# Script to generate and send test emails for local testing
# Requires: swaks (sudo apt-get install swaks or brew install swaks)
# Usage: ./scripts/test-emails.sh [smtp-host] [smtp-port]

SMTP_HOST="${1:-localhost}"
SMTP_PORT="${2:-25}"

echo "================================================"
echo "Sending test emails to $SMTP_HOST:$SMTP_PORT"
echo "================================================"

# Email 1: Simple text email
echo -e "\n[1/5] Sending simple text email..."
swaks --to testuser@example.com \
      --from sender1@test.com \
      --server "$SMTP_HOST:$SMTP_PORT" \
      --header "Subject: Test Email 1 - Simple Text" \
      --body "This is a simple test email generated by test script." \
      && echo "✓ Email 1 sent successfully" \
      || echo "✗ Failed to send email 1"

# Email 2: Email with HTML content
echo -e "\n[2/5] Sending HTML content email..."
swaks --to testuser@example.com \
      --from sender2@test.com \
      --server "$SMTP_HOST:$SMTP_PORT" \
      --header "Subject: Test Email 2 - HTML Content" \
      --body "<html><body><h1>Hello from Test Script</h1><p>This is an HTML email.</p></body></html>" \
      --add-header "Content-Type: text/html" \
      && echo "✓ Email 2 sent successfully" \
      || echo "✗ Failed to send email 2"

# Email 3: Email with special characters
echo -e "\n[3/5] Sending email with special characters..."
swaks --to testuser@example.com \
      --from sender3@test.com \
      --server "$SMTP_HOST:$SMTP_PORT" \
      --header "Subject: Test Email 3 - Special Chars: 日本語 🎉" \
      --body "Testing special characters: áéíóú ñ 中文 日本語 한글 🚀 ✅ 💯" \
      && echo "✓ Email 3 sent successfully" \
      || echo "✗ Failed to send email 3"

# Email 4: Email to different recipient
echo -e "\n[4/5] Sending email to different recipient..."
swaks --to anotheruser@example.com \
      --from automated@test.local \
      --server "$SMTP_HOST:$SMTP_PORT" \
      --header "Subject: Test Email 4 - Different Recipient" \
      --body "This email is sent to a different recipient for testing isolation." \
      && echo "✓ Email 4 sent successfully" \
      || echo "✗ Failed to send email 4"

# Email 5: Email with long body
echo -e "\n[5/5] Sending email with long content..."
swaks --to testuser@example.com \
      --from bulk@sender.com \
      --server "$SMTP_HOST:$SMTP_PORT" \
      --header "Subject: Test Email 5 - Long Content" \
      --body "$(printf 'Line %d: This is a test email with a longer body to verify the system handles larger content properly.\n' {1..50})" \
      && echo "✓ Email 5 sent successfully" \
      || echo "✗ Failed to send email 5"

echo -e "\n================================================"
echo "✓ All 5 test emails sent!"
echo "================================================"
echo ""
echo "To verify, check the API:"
echo "  curl \"http://localhost:48080/inbox?email=testuser@example.com\" | jq"
echo "  curl \"http://localhost:48080/inbox?email=anotheruser@example.com\" | jq"
echo ""
